version: '3.3'

services:
   db:
     image: mysql:5.7.26
     ports:
       - "13306:3306"
     volumes:
       - db_data:/var/lib/mysql
       - conf_mysql:/etc/my.cnf
     restart: unless-stopped
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     networks:
      - wordpress-network

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     volumes:
       - wordpress_files:/var/www/html
     restart: unless-stopped
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
     networks:
      - wordpress-network
   phpmyadmin:
     depends_on:
       - db
     image: corbinu/docker-phpmyadmin
     ports:
       - "8181:80"
     restart: unless-stopped
     environment:
       MYSQL_USERNAME: root
       MYSQL_ROOT_PASSWORD: somewordpress
     networks:
      - wordpress-network
volumes:
    db_data: {}
    conf_mysql: {}
    wordpress_files: {}
networks:
   wordpress-network:
       driver: bridge