version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - /var/tmp/mywordpress/db_data:/var/lib/mysql:rw
       - /var/tmp/mywordpress/conf_mysql:/etc/mysql/conf.d/my.cnf:rw
     ports:
       - "13306:3306"
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - /var/tmp/mywordpress/wordpress:/var/www/html/wp-content:rw
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
   
   phpmyadmin:
     depends_on:
       - db
     image: phpmyadmin/phpmyadmin
     restart: always 
     ports:
       - 8080:80
     environment:
       PMA_HOST: db
       MYSQL_ROOT_PASSWORD: somewordpress
volumes:
    db_data: {}
